[2023-04-15T23:35:10.461+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_1min.dump_1m scheduled__2023-04-15T23:30:00+00:00 [queued]>
[2023-04-15T23:35:10.543+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_1min.dump_1m scheduled__2023-04-15T23:30:00+00:00 [queued]>
[2023-04-15T23:35:10.546+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-15T23:35:10.582+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-15T23:35:10.588+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-15T23:35:10.714+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): dump_1m> on 2023-04-15 23:30:00+00:00
[2023-04-15T23:35:10.738+0000] {standard_task_runner.py:55} INFO - Started process 1454 to run task
[2023-04-15T23:35:10.759+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_1min', 'dump_1m', 'scheduled__2023-04-15T23:30:00+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/dag_1min.py', '--cfg-path', '/tmp/tmpqzl7e49c']
[2023-04-15T23:35:10.762+0000] {standard_task_runner.py:83} INFO - Job 331: Subtask dump_1m
[2023-04-15T23:35:11.263+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_1min.dump_1m scheduled__2023-04-15T23:30:00+00:00 [running]> on host cc609b5f7385
[2023-04-15T23:35:12.599+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_1min
AIRFLOW_CTX_TASK_ID=dump_1m
AIRFLOW_CTX_EXECUTION_DATE=2023-04-15T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-15T23:30:00+00:00
[2023-04-15T23:35:13.818+0000] {logging_mixin.py:137} WARNING -   0%|          | 0/2 [00:00<?, ?it/s]
[2023-04-15T23:35:14.999+0000] {logging_mixin.py:137} INFO - [*********************100%***********************]  1 of 1 completed
[2023-04-15T23:35:16.730+0000] {logging_mixin.py:137} WARNING -  50%|#####     | 1/2 [00:02<00:02,  2.90s/it]
[2023-04-15T23:35:17.653+0000] {logging_mixin.py:137} INFO - [*********************100%***********************]  1 of 1 completed
[2023-04-15T23:35:19.800+0000] {logging_mixin.py:137} WARNING - 100%|##########| 2/2 [00:05<00:00,  3.00s/it]
[2023-04-15T23:35:19.813+0000] {logging_mixin.py:137} WARNING - 100%|##########| 2/2 [00:05<00:00,  2.99s/it]
[2023-04-15T23:35:19.838+0000] {logging_mixin.py:137} INFO - Index(['open', 'high', 'low', 'close', 'adj_close', 'volume', 'timestamp',
       'currency_pair', 'exchangetimezonename', 'timezone'],
      dtype='object')
[2023-04-15T23:35:20.073+0000] {download_yahoo.py:57} INFO - Downloaded data: 
	         open       high        low  ...  currency_pair  exchangetimezonename  timezone
0  19.140894  19.140894  19.140894  ...       AVAX-USD                   UTC       UTC
1  19.134127  19.134127  19.134127  ...       AVAX-USD                   UTC       UTC
2  19.132166  19.132166  19.132166  ...       AVAX-USD                   UTC       UTC
3  19.134485  19.134485  19.134485  ...       AVAX-USD                   UTC       UTC
4  19.132874  19.132874  19.132874  ...       AVAX-USD                   UTC       UTC

[5 rows x 10 columns]
[2023-04-15T23:35:20.687+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-15T23:35:20.830+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=dag_1min, task_id=dump_1m, execution_date=20230415T233000, start_date=20230415T233510, end_date=20230415T233520
[2023-04-15T23:35:21.243+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-15T23:35:21.400+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-04-17T03:29:10.304+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_1min.dump_1m scheduled__2023-04-15T23:30:00+00:00 [queued]>
[2023-04-17T03:29:10.660+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_1min.dump_1m scheduled__2023-04-15T23:30:00+00:00 [queued]>
[2023-04-17T03:29:10.665+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-17T03:29:10.674+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-17T03:29:10.677+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-17T03:29:11.118+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): dump_1m> on 2023-04-15 23:30:00+00:00
[2023-04-17T03:29:11.192+0000] {standard_task_runner.py:55} INFO - Started process 165 to run task
[2023-04-17T03:29:11.276+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_1min', 'dump_1m', 'scheduled__2023-04-15T23:30:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_1min.py', '--cfg-path', '/tmp/tmpuuy3sh1s']
[2023-04-17T03:29:11.298+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask dump_1m
[2023-04-17T03:29:12.337+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_1min.dump_1m scheduled__2023-04-15T23:30:00+00:00 [running]> on host 731b4eac3d0f
[2023-04-17T03:29:21.654+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_1min
AIRFLOW_CTX_TASK_ID=dump_1m
AIRFLOW_CTX_EXECUTION_DATE=2023-04-15T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-15T23:30:00+00:00
[2023-04-17T03:29:27.648+0000] {logging_mixin.py:137} WARNING -   0%|          | 0/2 [00:00<?, ?it/s]
[2023-04-17T03:29:29.315+0000] {logging_mixin.py:137} INFO - [*********************100%***********************]  1 of 1 completed
[2023-04-17T03:29:30.887+0000] {logging_mixin.py:137} WARNING -  50%|#####     | 1/2 [00:03<00:03,  3.21s/it]
[2023-04-17T03:29:31.097+0000] {logging_mixin.py:137} INFO - [*********************100%***********************]  1 of 1 completed
[2023-04-17T03:29:31.099+0000] {logging_mixin.py:137} INFO - 
1 Failed download:
[2023-04-17T03:29:31.101+0000] {logging_mixin.py:137} INFO - - BTC-USD: Exception('Tkr BTC-USD tz already in cache')
[2023-04-17T03:29:32.308+0000] {logging_mixin.py:137} WARNING - 100%|##########| 2/2 [00:04<00:00,  2.16s/it]
[2023-04-17T03:29:32.314+0000] {logging_mixin.py:137} WARNING - 100%|##########| 2/2 [00:04<00:00,  2.32s/it]
[2023-04-17T03:29:32.330+0000] {logging_mixin.py:137} INFO - Index(['open', 'high', 'low', 'close', 'adj_close', 'volume', 'timestamp',
       'currency_pair', 'exchangetimezonename', 'timezone'],
      dtype='object')
[2023-04-17T03:29:32.433+0000] {download_yahoo.py:57} INFO - Downloaded data: 
	         open       high        low  ...  currency_pair  exchangetimezonename  timezone
0  19.108862  19.108862  19.108862  ...       AVAX-USD                   UTC       UTC
1  19.107136  19.107136  19.107136  ...       AVAX-USD                   UTC       UTC
2  19.105591  19.105591  19.105591  ...       AVAX-USD                   UTC       UTC
3  19.104191  19.104191  19.104191  ...       AVAX-USD                   UTC       UTC
4  19.103355  19.103355  19.103355  ...       AVAX-USD                   UTC       UTC

[5 rows x 10 columns]
[2023-04-17T03:29:32.437+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 540, in _validate_comparison_value
    self._check_compatible_with(other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 502, in _check_compatible_with
    self._assert_tzawareness_compat(other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 692, in _assert_tzawareness_compat
    "Cannot compare tz-naive and tz-aware datetime-like objects."
TypeError: Cannot compare tz-naive and tz-aware datetime-like objects.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 1008, in _cmp_method
    other = self._validate_comparison_value(other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 543, in _validate_comparison_value
    raise InvalidComparison(other) from err
pandas.core.arrays.datetimelike.InvalidComparison: 2023-04-15 23:58:00+00:00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_1min.py", line 19, in dump_1m
    dump_latest_data('yahoo_yfinance_spot_downloaded_1min','1m')
  File "/code/Latest_Data.py", line 42, in dump_latest_data
    p=k[k['timestamp']>start_timestamp]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 48, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 270, in comparison_op
    res_values = op(lvalues, rvalues)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 48, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/datetimelike.py", line 1010, in _cmp_method
    return invalid_comparison(self, other, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/invalid.py", line 34, in invalid_comparison
    raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")
TypeError: Invalid comparison between dtype=datetime64[ns] and Timestamp
