{"name": "test0", "status": "skipped", "statusDetails": {"message": "Skipped: This test fails on some computers due to AmpTask1649", "trace": "('/app/core/statistics/test/test_regression.py', 137, 'Skipped: This test fails on some computers due to AmpTask1649')"}, "description": "\n        Check that the randomly generated data is reproducible.\n        ", "start": 1656452752237, "stop": 1656452752237, "uuid": "4d1887e1-09e6-4e20-afb7-119c4315ce75", "historyId": "764fd8225e775c3239f749e3c6b98022", "testCaseId": "72f4b67d2734e1d7da7733b507895449", "fullName": "core.statistics.test.test_regression.TestComputeRegressionCoefficients2#test0", "labels": [{"name": "tag", "value": "@pytest.mark.skip(reason='This test fails on some computers due to AmpTask1649')"}, {"name": "parentSuite", "value": "core.statistics.test"}, {"name": "suite", "value": "test_regression"}, {"name": "subSuite", "value": "TestComputeRegressionCoefficients2"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "core.statistics.test.test_regression"}]}