{"name": "test_serial1", "status": "passed", "description": "\n        Execute:\n        - 3 experiments with one failing\n        - serially\n        - aborting on error\n        ", "attachments": [{"name": "log", "source": "0ff51a1e-a589-4ba8-9eab-b7ad36f68b9b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ad909e17-df5a-4e53-a647-575c13e66e99-attachment.txt", "type": "text/plain"}], "start": 1656452480033, "stop": 1656452497271, "uuid": "86f75c72-a56a-4259-bf62-91188526bb87", "historyId": "5ba60960e930b1c5b605fc3e4fa26505", "testCaseId": "e83962aabacd36307a4ae54e7607b254", "fullName": "dataflow.model.test.test_run_experiment.TestRunExperimentFail2#test_serial1", "labels": [{"name": "tag", "value": "slow"}, {"name": "parentSuite", "value": "dataflow.model.test"}, {"name": "suite", "value": "test_run_experiment"}, {"name": "subSuite", "value": "TestRunExperimentFail2"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "dataflow.model.test.test_run_experiment"}]}