17:32:49 - [36mINFO [0m hunit_test.py setUp:912            
################################################################################
TestCheckDataFrame1.test_check_df_not_equal1
################################################################################
17:32:49 - [31mERROR[0m hunit_test.py _check_df_compare_outcome:1589           Dataframe values are not close
17:32:49 - [31mERROR[0m hunit_test.py _to_error:1687                           actual=
   a     b  c
0  0  1.06  2
1  3  4.00  5
17:32:49 - [31mERROR[0m hunit_test.py _to_error:1687                           expected=
   a  b  c
0  0  1  2
1  3  4  5
17:32:49 - [31mERROR[0m hunit_test.py _to_error:1687                           actual_masked=
[[ nan 1.06  nan]
 [ nan  nan  nan]]
17:32:49 - [31mERROR[0m hunit_test.py _to_error:1687                           expected_masked=
[[nan  1. nan]
 [nan nan nan]]
17:32:49 - [31mERROR[0m hunit_test.py _to_error:1687                           err=
[[ nan 0.06  nan]
 [ nan  nan  nan]]
17:32:49 - [31mERROR[0m hunit_test.py _to_error:1687                           max_err=0.060
17:32:49 - [31mERROR[0m hunit_test.py assert_equal:823                         
================================================================================
Test 'TestCheckDataFrame1.test_check_df_not_equal1' failed
================================================================================
17:32:49 - [36mINFO [0m hunit_test.py assert_equal:855                         Saved exp_var in tmp.exp_var.txt
