{"name": "test_check_same_configs_error", "status": "passed", "description": "\n        Verify that an error is raised when duplicated configs are encountered.\n        ", "attachments": [{"name": "log", "source": "44aa243e-0718-4754-a2eb-b37ae245019a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "5bfec976-fe27-4e0f-9e27-462012a02d1d-attachment.txt", "type": "text/plain"}], "start": 1656452818092, "stop": 1656452818096, "uuid": "ebcb07db-7135-44b9-8069-722ea42564f9", "historyId": "ecd550f96bd1f4e910b340657706994b", "testCaseId": "6c31c6c62530ad7d30fa3f4050655c96", "fullName": "core.config.test.test_config_utils.Test_validate_configs1#test_check_same_configs_error", "labels": [{"name": "parentSuite", "value": "core.config.test"}, {"name": "suite", "value": "test_config_utils"}, {"name": "subSuite", "value": "Test_validate_configs1"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "core.config.test.test_config_utils"}]}