{"name": "test0", "status": "skipped", "statusDetails": {"message": "Skipped: This test fails on some computers due to AmpTask1649", "trace": "('/app/dataflow/core/nodes/test/test_regression_models.py', 35, 'Skipped: This test fails on some computers due to AmpTask1649')"}, "description": "\n        Check that the randomly generated data is the same as our development\n        computers.\n        ", "start": 1656452841936, "stop": 1656452841936, "uuid": "e1567346-b265-41e3-9033-f2d002d1f53e", "historyId": "b6fa866aaae3bfd94f3d1e7b981d2fb1", "testCaseId": "3fa63c76e471099db7a44252055cbbe0", "fullName": "dataflow.core.nodes.test.test_regression_models.TestLinearRegression#test0", "labels": [{"name": "tag", "value": "@pytest.mark.skip(reason='This test fails on some computers due to AmpTask1649')"}, {"name": "parentSuite", "value": "dataflow.core.nodes.test"}, {"name": "suite", "value": "test_regression_models"}, {"name": "subSuite", "value": "TestLinearRegression"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "dataflow.core.nodes.test.test_regression_models"}]}