[32mINFO    [0m helpers.hunit_test:hunit_test.py:912 17:37:49 - [36mINFO [0m hunit_test.py setUp:912            17:37:49 - [36mINFO [0m hunit_test.py setUp:912            
################################################################################
Test_pytest_repro1.test_files1
################################################################################
[32mINFO    [0m helpers.lib_tasks_pytest:lib_tasks_pytest.py:830 17:37:49 - [36mINFO [0m lib_tasks_pytest.py pytest_repro:830                   17:37:49 - [36mINFO [0m lib_tasks_pytest.py pytest_repro:830                   Reading file_name='/app/helpers/test/outcomes/Test_pytest_repro1.test_files1/tmp.scratch/cache/lastfailed'
[32mINFO    [0m helpers.lib_tasks_pytest:lib_tasks_pytest.py:832 17:37:49 - [36mINFO [0m lib_tasks_pytest.py pytest_repro:832                   17:37:49 - [36mINFO [0m lib_tasks_pytest.py pytest_repro:832                   Reading failed tests from file '/app/helpers/test/outcomes/Test_pytest_repro1.test_files1/tmp.scratch/cache/lastfailed'
[32mINFO    [0m helpers.lib_tasks_pytest:lib_tasks_pytest.py:943 17:37:49 - [36mINFO [0m lib_tasks_pytest.py pytest_repro:943                   17:37:49 - [36mINFO [0m lib_tasks_pytest.py pytest_repro:943                   Found 7 failed pytest 'files' target(s); to reproduce run:
pytest dev_scripts/testing/test/test_run_tests.py
pytest dev_scripts/testing/test/test_run_tests2.py
pytest helpers/test/test_printing.py
pytest documentation/scripts/test/test_all.py
pytest documentation/scripts/test/test_render_md.py
pytest helpers/test/helpers/test/test_list.py
pytest helpers/test/test_cache.py