{"name": "test_serial2", "status": "passed", "description": "\n        Execute:\n        - a workload with 5 tasks that succeed and 1 task that fails\n        - serially\n        - don't abort because abort_on_error=False\n        ", "attachments": [{"name": "log", "source": "555b0ed3-b810-42c5-be1a-27f397a58b25-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "f0c69252-1e26-4e98-8d9b-690eb7cbc9b2-attachment.txt", "type": "text/plain"}], "start": 1656452662130, "stop": 1656452662208, "uuid": "325a4180-38b7-4982-a124-391e1b44a0f3", "historyId": "cb4cc4c64681501b3ab652de4552f887", "testCaseId": "43e2908740f46ad99e01d52f87af0f4d", "fullName": "helpers.test.test_joblib_helpers.Test_parallel_execute3#test_serial2", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_joblib_helpers"}, {"name": "subSuite", "value": "Test_parallel_execute3"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_joblib_helpers"}]}